name: PyLops Testing (CuPy)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install uv with Python 3.11
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11
      - name: Install dependencies and pylops
        run: |
          srun --account=yuxilab -n 1 -N 1 --gres=gpu:L40S:1 bash -c '
            uv sync --locked  --extra advanced \
              --extra stat --extra gpu-cu12 \
              --extra deep-cu128 --all-groups
          '
          echo "done!"
      - name: Test with pytest
        run: |
          srun --account=yuxilab -n 1 -N 1 --gres=gpu:L40S:1 bash -c '
            export NUMBA_CUDA_DEFAULT_PTX_CC=8.9
            export CUPY_PYLOPS=1
            export TEST_CUPY_PYLOPS=1
            uv run pytest --color=yes pytests/
          '
          echo "done!"
